
import os
import sys
import logging
from typing import Sequence, MutableSequence

from Bio.SeqRecord import SeqRecord
from Bio.SeqFeature import SeqFeature

import src.output as out
import src.obtain_coverage as oc
import src.dedupl_features as ddf
import src.highlight_features as hlft
import src.parse_fasta_reference as pfr
from src.platform import platf_depend_exit
from src.coverage_array import CoverageArray
from src.error import CoverageValidationError
from src.filter_features import filter_features
from src.arguments import parse_arguments, HighlighterArgs
from src.coverage_thresholds.lower_coverage_threshold import LowerCoverageThreshold
from src.coverage_thresholds.upper_coverage_threshold import UpperCoverageThreshold, \
                                                             UpperMedianCoverageThreshold


def main(version: str, last_update_date: str) -> None:

    args: HighlighterArgs = parse_arguments()

    # This string will be used for annotation of result GenBank file
    base_feature_note: str = f'generated by con-hi v{version}'

    has_warnings: bool = False

    # Read fasta records from input file
    logging.info('Parsing fasta from `{}`...'.format(args.target_fasta_fpath))
    fasta_records: Sequence[SeqRecord] = pfr.parse_fasta_reference(
        args.target_fasta_fpath,
        args.target_seq_ids
    )
    logging.info('Fasta parsing completed.')
    sys.stderr.write('=' * 20 + '\n')

    _create_outdir_from_outfile(args.outfpath)
    out.create_or_emply_file(args.outfpath)

    # Proceed with annotation
    for record in fasta_records:

        logging.info(f'Annotation started: `{record.description}`.')

        try:
            cov_array: CoverageArray = _get_coverage(
                args.bam_fpath,
                args.outfpath,
                record
            )
        except CoverageValidationError as err:
            logging.warning(str(err))
            has_warnings = True
            continue
        # end try

        record = _annotate_sequence_features(
            record,
            cov_array,
            args,
            base_feature_note
        )
        _write_output(record, cov_array, args)


        coverage_fpath: str = out.conf_path_to_depth_file(
            args.outfpath,
            record.id
        )
        if not args.keep_tmp_cov_file:
            _try_rm_temp_file(coverage_fpath)
        # end if

        sys.stderr.write('=' * 20 + '\n')
    # end for

    warning_msg: str = ' with warnings' if has_warnings else ''
    logging.info(f'Completed{warning_msg}! Fare you well!')
# end def


def _create_outdir_from_outfile(outfpath: str) -> None:
    # Function creates output directory
    # :param outfpath: path to output file;

    outdpath = os.path.dirname(outfpath)

    # Create directory if it does not exist
    if not os.path.isdir(outdpath):
        try:
            os.makedirs(outdpath)
        except OSError as err:
            logging.error(f'Cannot create output directory `{outdpath}`.')
            logging.error(str(err))
            platf_depend_exit(1)
        # end try
    # end if
# end def


def _try_rm_temp_file(file_path):
    try:
        os.unlink(file_path)
    except OSError as err:
        logging.warning('Cannot remove temporary file `{}`'.format(file_path))
        logging.warning(str(err))
    # end try
# end def


def _make_coverage_thresholds(args, cov_array):
    lower_coverage_thresholds = [
        LowerCoverageThreshold(thr_int)
            for thr_int in args.lower_coverage_thresholds
    ]
    upper_coverage_thresholds = [
        UpperCoverageThreshold(thr_int)
            for thr_int in args.upper_coverage_thresholds
    ]

    median_coverage = cov_array.median_coverage
    upper_median_coverage_thresholds = [
        UpperMedianCoverageThreshold(coef_float, median_coverage)
            for coef_float in args.upper_coverage_coefficients
    ]

    return lower_coverage_thresholds \
           + upper_coverage_thresholds \
           + upper_median_coverage_thresholds
# end def


def _get_coverage(bam_fpath: str,
                  outfpath: str,
                  record: SeqRecord) -> CoverageArray:
    # Function obtains and validates coverage for a sequence
    # :param bam_fpath: path to BAM file;
    # :param outfpath: path to output file;
    # :param record: sequence record;
    # :raises CoverageValidationError: if coverage validation fails;

    coverage_fpath: str = out.conf_path_to_depth_file(outfpath, record.id)

    logging.info('Silently counting coverages with `samtools depth`...')
    cov_fpath: str = oc.count_coverage(
        bam_fpath,
        record.id,
        coverage_fpath
    )
    logging.info('Coverage counting completed.')

    try:
        cov_array: CoverageArray = oc.get_coverage_for_reference(cov_fpath)
    except oc.MissingCoveragesError:
        raise CoverageValidationError(
            'Coverage values for this sequence are not found'
        )
    # end try

    if len(cov_array) == 0:
        raise CoverageValidationError(
            f'No coverage information found for sequence `{record.id}`. '
            'Please, make sure that field `RNAME` (3-rd column) in your BAM file contains '
            f'id of this sequence specified in fasta header (i.e. `{record.id}`). '
            'Skipping this sequence.'
        )
    # end if

    if len(cov_array) != len(record.seq):
        raise CoverageValidationError(
            f'Length of sequence `{record.id}` ({len(record.seq)} bp) '
            f'is not equal to number of coverage positions ({len(cov_array)}) reported by `samtools depth` '
            f'and stored in coverage file `{cov_fpath}`. '
            'Re-creating the bam file might be the solution of this issue. '
            'Skipping this sequence.'
        )
    # end if

    return cov_array
# end def


def _annotate_sequence_features(record: SeqRecord,
                                cov_array: CoverageArray,
                                args: HighlighterArgs,
                                base_feature_note: str) -> SeqRecord:
    # Function annotates features on a sequence record
    # :param record: sequence record to annotate;
    # :param cov_array: coverage array;
    # :param args: program arguments;
    # :param base_feature_note: note for features;

    cov_thresholds = _make_coverage_thresholds(args, cov_array)

    for cov_threshold in cov_thresholds:
        logging.info(f'Screening the sequence for regions of {cov_threshold.get_label()}...')

        coverage_features = hlft.highlight_coverage_features(
            cov_array,
            cov_threshold,
            base_feature_note
        )

        coverage_features = filter_features(coverage_features, args.min_feature_len)
        coverage_features = ddf.dedupl_features(coverage_features, record.features)

        record.features.extend(coverage_features)
        sum_feature_lengths: int = sum(
            map(len, coverage_features)
        )
        logging.info(
            'Regions of {} annotated. Totally, {:,} bp long.'.format(
                cov_threshold.get_label(),
                sum_feature_lengths
            )
        )
    # end for

    return record
# end def


def _write_output(record: SeqRecord,
                  cov_array: CoverageArray,
                  args: HighlighterArgs) -> None:
    # Function writes annotated sequence to output file
    # :param record: sequence record to write;
    # :param cov_array: coverage array;
    # :param args: program arguments;

    logging.info('Saving annotated sequence...')

    if args.output_format == 'genbank':
        out.write_genbank_output(
            record,
            args.topology,
            args.organism,
            cov_array,
            args.outfpath
        )
    else:
        out.write_bed_output(
            record,
            cov_array,
            args.outfpath
        )
    # end if

    logging.info(f'Annotated sequence saved to `{args.outfpath}`.')
# end def
