
def print_help(version: str, last_update_date: str) -> None:
    print('=== consensus-highlighter ===')
    print(f'Version {version}; {last_update_date} edition.')
    print('\n## Description')
    print('  This program annotates low-coverage regions of sequences in fasta format.')
    print('### Input')
    print('  1. Target sequence(s) in fasta format.')
    print('  2. Mapping in **sorted** BAM file.')
    print('  3. Coverage threshold(s) for searching low-coverage regions.')
    print('### Output')
    print('  - GenBank file with annotated low-coverage regions.')
    print('\n## Usage')
    print('Basic usage is:')
    print('    `./consensus-highlighter.py -f <TARGET_FASTA> -b <MAPPING_BAM>`')
    print('You can specify custom coverage theshold(s) by passing comma-separated list of thresholds')
    print('  with option `-c`. For example, following command will annotate all regions')
    print('  with coverage below 25 and all regions below 55 (and also with zero coverage):')
    print('    `./consensus-highlighter.py -f my_sequence.fasta -b my_mapping.sorted.bam -c 25,55`')
    print('\n### Options (* - mandatory option)')
    print('-f or --target-fasta: *')
    print('    File of target sequence(s) in fasta format.')
    print('-b or --bam: *')
    print('    Sorted BAM file which contains mapping on target sequence(s).')
    print('-o or --outfile:')
    print('    Output file.')
    print("    Default value: `highlighted_sequence.gbk`.")
    print('-c or --coverage-thresholds:')
    print('    Comma-separated list of coverage threshold(s).')
    print('    Default: 10.')
    print('    To disable it, specify `-c off`.')
    print('-n or --no-zero-output:')
    print('    Disable annotation of zero-coverage regions.')
    print('    Disabled by default.')
    print('-C or --upper-coverage-coefficients:')
    print('    Comma-separated list of coverage coefficient(s).')
    print('    To annotate regions with coverage > 1.7×M,')
    print('      where M is median coverage, specify `-C 1.7`.')
    print('    Default: 2.0.')
    print('    To disable it, specify `-C off`.')
    print('-l or --min-feature-len:')
    print('    Minimum length of a feature to output. Must be int >= 0.')
    print('    Default: 5 bp.')
    print('--circular:')
    print('    Target sequence in curcular. Affects only corresponding GenBank field.')
    print('    Disabled by default.')
    print('--organism:')
    print('    Organism name. Affects only corresponding GenBank field.')
    print('    If it contains spaces, surround it with quotes.')
    print('    Empty by default.')
    print('-k or --keep-temp-cov-file:')
    print("    Don't delete temporary TSV file `coverages.tsv` after work of the program.")
    print('    The program creates this file in the same directory where the "-o" file is located.')
    print('    Default behaviour is to delete this file afterwards.')
    print()
# end def
