# -*- encoding: utf-8 -*-
# Version 1.0.a

def print_help(version: str, last_update_date: str) -> None:
    print('=== consensus-highlighter ===')
    print(f'Version {version}; {last_update_date} edition.')
    print('\n## Description')
    print('  This program annotates low-coverage regions of sequences in fasta format.')
    print('### Input')
    print('  1. Target sequence(s) in fasta format.')
    print('  2. Mapping in **sorted** BAM file.')
    print('  3. Coverage threshold(s) for searching low-coverage regions.')
    print('### Output')
    print('  - GenBank file with annotated low-coverage regions.')
    print('\n## Usage')
    print('Basic usage is:')
    print('    `./consensus-highlighter.py -f <TARGET_FASTA> -b <MAPPING_BAM>`')
    print('You can specify custom coverage theshold(s) by passing comma-separated list of thresholds')
    print('  with option `-c`. For example, following command will annotate all regions')
    print('  with coverage below 25 and all regions below 55 (and also with zero coverage):')
    print('    `./consensus-highlighter.py -f my_sequence.fasta -b my_mapping.sorted.bam -c 25,55`')
    print('\n### Options (* - mandatory option)')
    print('-f or --target-fasta: *')
    print('    File of target sequence(s) in fasta format.')
    print('-b or --bam: *')
    print('    Sorted BAM file which contains mapping on target sequence(s).')
    print('-o or --outdir:')
    print('    Output directory.')
    print("    Default value: 'consensus-highlighter-output'.")
    print('-c or --coverage-thresholds:')
    print('    Comma-separated list of coverage threshold(s).')
    print('    Default: 10.')
    print('-n or --no-zero-output:')
    print('    Suppress annotation of zero-coverage regions.')
    print('    Disabled by default.')
    print('--circular:')
    print('    Target sequence in curcular. Affects only corresponding GenBank field.')
    print('    Disabled by default.')
    print('--organism:')
    print('    Organism name. Affects only corresponding GenBank field.')
    print('    If it contains spaces, surround it with quotes.')
    print('    Empty by default.')
    print('--prefix:')
    print('    Prefix for output files.')
    print('    Empty by default.')
    print()
# end def print_help
